version: '3.9'

services:
  database:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # Only needed if you want to access from the host machine
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet || exit 1"] # Corrected healthcheck
      interval: 10s
      timeout: 5s
      retries: 12
    environment:
      MONGO_INITDB_DATABASE: ports

  backend:
    build:
      context: ./port_finder_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/usr/src/app/data:ro # Correctly mount the CSV file here
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/ports
    depends_on:
      database:
        condition: service_healthy

  client:
    build:
      context: ./port_finder_client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production

volumes:
  mongo-data: